config/routes.rb
Rails.application.routes.draw do

# 会員用
# ↓2023/08/21記入
scope module: :public do
  root to: "homes#top"
  resources :items, only: [:index, :show]
  get "/customers/confirm_withdraw" => "customers#confirm_withdraw"
  get "/customers/mypage" => "customers#show"
  get "/customers/information/edit" => "customers#edit"
  patch "customers/information" => "customers#update"
  patch "/customers/withdraw" => "customers#withdraw"
  delete "/cart_items/destroy_all" => "cart_items#destroy_all"
  resources :cart_items, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :show, :create, :new]
  post "orders/confirm" => "orders#confirm"
  get "orders/complete" => "orders#complete"
  resources :destinations, only: [:index, :edit, :create, :update, :destroy]
  get 'homes/about'

end
# ↑2023/08/21記入
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# ↓2023/08/21記入
namespace :admin do

  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update, :index]
  resources :order_details, only: [:update]
end
# ↑2023/08/21記入

# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  get 'homes/about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :destinations, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    last_name + '' + first_name
  end

  def full_name_kana
    last_name_kana + '' + first_name_kana
  end

  def customer_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :customer
  validates :name, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true, format: {with: /\A\d{7}\z/}, numericality: { only_integer: true }
  
  def destination_display
    '〒' + postal_code + ' ' + name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  enum is_selling_status: { no_selling: 0, selling: 1}

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_datails

  has_one_attached :items_img


  validates :name, presence: true
  validates :is_selling_status, presence: true
  validates :explanation, presence: true
  validates :genre, presence: true
  validates :unit_price, presence: true, numericality: {only_integer: true, greater_than: 0}

  def get_items_image(width, height)
  unless items_img.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    items_img.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  items_img.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  enum how_to_pay: { credit_card: 0, transfer: 1 }
  
  enum status: { 
    Awaiting_Payment: 0,
    Payment_Confirmed: 1,
    In_Production: 2,
    Preparing_for_Shipment: 3,
    Shipped: 4
  }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customers = Customer.find(params[:id])
  end

  def edit
    @customers = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customers_path(customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :address, :post_code, :phone_number, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "ジャンルを追加しました"
    else
      flash.now[:danger] = "エラーが発生しました"
      @genres = Genre.all
      render "index"
    end
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンルを変更しました"
    else
      flash.now[:danger] = "エラーが発生しました"
      render "edit"
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end 
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
#aaaa
  def index
    @item = Item.new
    @items =Item.all
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    # logger.debug "Received item_params: #{item_params.inspect}"
    @item = Item.new(item_params)
    if @item.save!
      # logger.debug "Received item_params: #{item_params.inspect}"
      flash.now[:success] = "商品の新規登録が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:danger] = "商品の新規登録内容に不備があります。"
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
     if @item.update!(item_params)
       flash.now[:success] = "商品詳細の変更が完了しました。"
       redirect_to admin_item_path(@item)
     else
       flash.now[:danger] = "商品詳細の変更内容に不備があります。"
       render :edit
     end
  end
end

private

  def item_params
    params.require(:item).permit(:genre_id, :name, :explanation, :items_img, :unit_price, :is_selling_status, :is_active)
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container-fluid" style="background-image: url('<%= asset_path('大理石.jpg') %>');
background-size: cover; background-position: center center;height: 100vh;">
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5"><%= @customers.full_name %>さんの会員情報編集</h4>
      <table class="table table-borderless">
        <%= form_with model: [:admin, @customers] do |f| %>
        <tr>
          <td>会員ID</td>
          <td><%= @customers.id %></td>
        </tr>

        <tr>
          <td>氏名</td>
          <td><%= f.text_field :last_name %>　<%= f.text_field :first_name %></td>
        </tr>

        <tr>
          <td>フリガナ</td>
          <td><%= f.text_field :last_name_kana %>　<%= f.text_field :first_name_kana %></td>
        </tr>

        <tr>
          <td>郵便番号</td>
          <td><%= f.text_field :post_code %></td>
          <td></td>
        </tr>

        <tr>
          <td>住所</td>
          <td><%= f.text_field :address %></td>
          <td></td>
        </tr>

        <tr>
          <td>電話番号</td>
          <td><%= f.text_field :phone_number %></td>
          <td></td>
        </tr>

        <tr>
          <td>メールアドレス</td>
          <td><%= f.text_field :email %></td>
          <td></td>
        </tr>

        <tr>
          <td>会員ステータス</td>
          <td>
            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, "有効", { value: :true }  %>

            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "退会", { value: :false } %>
          </td>
        </tr>

        <tr>
          <td></td>
          <td><%= f.submit "変更を保存", class:"btn btn-success" %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
</div>

app/views/admin/customers/index.html.erb
<div class="container-fluid" style="background-image: url('<%= asset_path('大理石.jpg') %>');
background-size: cover; background-position: center center;height: 100vh;">
  
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5">会員一覧</h4>
        <table class="table">
          <thead>
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to customer.full_name, admin_customer_path(customer) %></td>
              <td><%= customer.email %></td>
              <td><%= customer.customer_status %></td>
            </tr>
          <% end %>
        </table>
    </div>
  </div>
</div>
</div>

app/views/admin/customers/show.html.erb
<div class="container-fluid" style="background-image: url('<%= asset_path('大理石.jpg') %>');
background-size: cover; background-position: center center;height: 100vh;">
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5"><%= @customers.full_name %>さんの会員詳細</h4>
      <div class="d-flex align-items-center">
        <table class="table table-borderless">
          <tr>
            <th>会員ID</td>
            <td><%= @customers.id %></td>
          </tr>
          <tr>
            <th>氏名</td>
            <td><%= @customers.last_name %>　<%= @customers.first_name %></td>
          </tr>

          <tr>
            <th>フリガナ</th>
            <td><%= @customers.last_name_kana %>　<%= @customers.first_name_kana %></td>
          </tr>

          <tr>
            <th>郵便番号</th>
            <td><%= @customers.post_code %></td>
          </tr>

          <tr>
            <th>住所</th>
            <td><%= @customers.address %></td>
          </tr>

          <tr>
            <th>電話番号</th>
            <td><%= @customers.phone_number %></td>
          </tr>

          <tr>
            <th>メールアドレス</th>
            <td><%= @customers.email %></td>
          </tr>

          <tr>
            <th>会員ステータス</th>
            <th><%= @customers.customer_status %></th>
          </tr>

          <tr>
            <td></td>
            <td><%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success" %>
            <%= link_to "注文履歴一覧を見る", admin_orders_path, class:"btn btn-primary" %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
</div>