config/routes.rb
Rails.application.routes.draw do

# 会員用
# ↓2023/08/21記入
scope module: :public do
  root to: "homes#top"
  resources :items, only: [:index, :show]
  get "/customers/confirm_withdraw" => "customers#confirm_withdraw"
  get "/customers/mypage" => "customers#show"
  get "/customers/information/edit" => "customers#edit"
  patch "customers/information" => "customers#update"
  patch "/customers/withdraw" => "customers#withdraw"
  delete "/cart_items/destroy_all" => "cart_items#destroy_all"
  resources :cart_items, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :show, :create, :new]
  post "orders/confirm" => "orders#confirm"
  get "orders/complete" => "orders#complete"
  resources :destinations, only: [:index, :edit, :create, :update, :destroy]
  get 'homes/about'

end
# ↑2023/08/21記入
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# ↓2023/08/21記入
namespace :admin do

  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update, :index]
  resources :order_details, only: [:update]
end
# ↑2023/08/21記入

# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  get 'homes/about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :destinations, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    last_name + '' + first_name
  end

  def full_name_kana
    last_name_kana + '' + first_name_kana
  end

  def customer_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :customer
  validates :name, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true, format: {with: /\A\d{7}\z/}, numericality: { only_integer: true }
  
  def destination_display
    '〒' + postal_code + ' ' + name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  enum is_selling_status: { no_selling: 0, selling: 1}

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_datails

  has_one_attached :items_img


  validates :name, presence: true
  validates :is_selling_status, presence: true
  validates :explanation, presence: true
  validates :genre, presence: true
  validates :unit_price, presence: true, numericality: {only_integer: true, greater_than: 0}

  def get_items_image(width, height)
  unless items_img.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    items_img.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  items_img.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  enum how_to_pay: { credit_card: 0, transfer: 1 }
  
  enum status: { 
    Awaiting_Payment: 0,
    Payment_Confirmed: 1,
    In_Production: 2,
    Preparing_for_Shipment: 3,
    Shipped: 4
  }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "ジャンルを追加しました"
    else
      flash.now[:danger] = "エラーが発生しました"
      @genres = Genre.all
      render "index"
    end
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンルを変更しました"
    else
      flash.now[:danger] = "エラーが発生しました"
      render "edit"
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end 
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
#aaaa
  def index
    @item = Item.new
    @items =Item.all
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    # logger.debug "Received item_params: #{item_params.inspect}"
    @item = Item.new(item_params)
    if @item.save!
      # logger.debug "Received item_params: #{item_params.inspect}"
      flash.now[:success] = "商品の新規登録が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:danger] = "商品の新規登録内容に不備があります。"
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
     if @item.update!(item_params)
       flash.now[:success] = "商品詳細の変更が完了しました。"
       redirect_to admin_item_path(@item)
     else
       flash.now[:danger] = "商品詳細の変更内容に不備があります。"
       render :edit
     end
  end
end

private

  def item_params
    params.require(:item).permit(:genre_id, :name, :explanation, :items_img, :unit_price, :is_selling_status, :is_active)
  end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
  end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/_genre_sidebar.html.erb
<!--<table class="genre-table table table-bordered table-hover">-->
  <!--<thead class="genre-thead">-->
    <!--<tr>-->
      <!--<th class="active">ジャンル検索</th>-->
    <!--</tr>-->
  <!--</thead>-->

  <!--<tbody>-->
     <%# genres.each do |genre| %>
      <!--<tr>-->
        <!--<td>-->
          <!--<%#= link_to items_path(genre_id: genre.id) do %>-->
            <!--<%#= genre.name %>-->
          <!--<%# end %>-->
        <!--</td>-->
      <!--</tr>-->
    <!--<%# end %>-->
  <!--</tbody>-->
 <!--</table>-->

app/views/admin/genres/edit.html.erb
<div class="container-fluid" style="background-image: url('<%= asset_path('大理石.jpg') %>');
background-size: cover; background-position: center center;height: 100vh;">
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h2>ジャンル編集</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <%= form_with model: @genre, url: admin_genre_path(@genre.id) do |f| %>
      <table>
        <tbody>
          <tr>
            <td class="pr-5">ジャンル名</td>
            <td><%= f.text_field :name %></td>
            <td class="pl-5"><%= f.submit "変更を保存", class: "btn btn-success" %></td>
          </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/admin/genres/index.html.erb
<div class="container-fluid" style="background-image: url('<%= asset_path('大理石.jpg') %>');
background-size: cover; background-position: center center;height: 100vh;">
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <h2>ジャンル一覧・追加</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-5 py-3">
      <%= form_with model: @genre, url: admin_genres_path do |f|%>
      <table>
        <tbody>
          <tr>
            <td>ジャンル名</td>
            <td><%= f.text_field :name %></td>
            <td><%= f.submit "新規投稿", class: "btn btn-info" %></td>
          </tr>
        </tbody>
      </table>
      <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-5">
      <table>
        <thead>
          <th class="py-2">ジャンル</th>
          <th></th>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>
  </div>
  </div>

app/views/admin/items/edit.html.erb
<div class="container-fluid" style="background-image: url('<%= asset_path('大理石.jpg') %>');
background-size: cover; background-position: center center;height: 100vh;">
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>商品編集</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <%= form_with model: @item, url: admin_item_path(@item), method: :patch, local: true do |f| %>

        <table>
          <tbody>
          <tr>
            <th><%= f.label :商品画像 %></th>
            <th><%= image_tag @item.get_items_image(100,100)  %></th>
          </tr>
          <tr>
            <th><%= f.label :商品画像を変更 %></th>
            <td><%= f.file_field image_tag @item.get_items_image(100,100) %></td>
          </tr>
          <tr>
            <th><%= f.label :商品名 %></th>
            <td><%= f.text_field :name, placeholder:"商品名" %></td>
          </tr>
          <tr>
            <th><%= f.label :商品説明 %></th>
            <!--<td><%#= f.text_area :explanation, rows: 3, cols: 50 %></td>-->
            <td><%= f.text_area :explanation, rows: 5, cols: 22, placeholder:"ここに説明文を記述します" %></td>
          </tr>
          <tr>
            <th><%= f.label :ジャンル %></th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--" %></td>
          </tr>
          <tr>
            <th><%= f.label :税抜価格 %></th>
            <td><%= f.text_field :unit_price, placeholder:"1000" %>円</td>
          </tr>
   　　   <tr>
  <th><%= f.label :販売ステータス %></th>
  <td>
    <%= f.radio_button :is_selling_status, "selling", checked: @item.is_selling_status == 1 %>
    <%= f.label :is_selling_status, "販売中" %>
    <%= f.radio_button :is_selling_status, "no_selling", checked: @item.is_selling_status == 0 %>
    <%= f.label :is_selling_status, "販売停止中" %>
  </td>
</tr>



          <tr>
            <th><%= f.submit "変更を保存", class: "btn btn-success" %></th>
          </tr>
          </tbody>
        </table>
        <% end %>
    </div>
  </div>
</div>
</div>

app/views/admin/items/index.html.erb
<div class="container-fluid" style="background-image: url('<%= asset_path('大理石.jpg') %>');
background-size: cover; background-position: center center;height: 100vh;">
  
<div class="container">
  <div class="row">
    <div class="col-auto">
      <%= link_to new_admin_item_path, class: 'plus-button' do %>
      <i class="fas fa-plus"></i>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <h2>商品一覧</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <table class="table">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜き価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name, admin_item_path(item.id) %></td>
              <td><%= item.unit_price %></td>
              <td><%= item.genre.name %></td>
              <td>
                <% if item.no_selling? %>
                  <%= Item.is_selling_statuses_i18n[:no_selling] %>
                <% elsif item.selling? %>
                  <%= Item.is_selling_statuses_i18n[:selling] %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/admin/items/new.html.erb
<div class="container-fluid" style="background-image: url('<%= asset_path('大理石.jpg') %>');
background-size: cover; background-position: center center;height: 100vh;">
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>商品新規登録</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <%= form_with model: @item, url: admin_items_path do |f| %>

        <table>
          <tr>
            <th><%= f.label :商品画像 %></th>
            <th><%= f.file_field :image %></th>
          </tr>
          <tr>
            <th><%= f.label :商品名 %></th>
            <td><%= f.text_field :name, placeholder:"商品名" %></td>
          </tr>
          <tr>
            <th><%= f.label :商品説明 %></th>
            <td><%= f.text_area :explanation, class: "form_control",rows: 5, placeholder:"ここに説明文を記述します" %></td>
          </tr>
          <tr>
            <th><%= f.label :ジャンル %></th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--" %></td>
          </tr>
          <tr>
            <th><%= f.label :税抜価格 %></th>
            <td><%= f.text_field :unit_price, placeholder:"1000" %>円</td>
          </tr>
          <tr>
            <th><%= f.label :販売ステータス %></th>
            <td>
              <%= f.radio_button :is_selling_status, "selling", checked: true %>
              <%= f.label :is_selling_status, "販売中" %>
              <%= f.radio_button :is_selling_status, "販売停止" %>
              <%= f.label :is_selling_status, "販売停止中" %>
            </td>
          </tr>
          <tr>
            <th><%= f.submit "新規登録", class: "btn btn-success" %></th>
          </tr>
        </table>
        <% end %>
    </div>
  </div>
</div>
</di

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>商品詳細</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
        <%= image_tag @item.get_items_image(100,100) %>
    </div>
    <div class="col-md-6">
      <table>
      <tr>
        <th>商品名</th>
        <td><%= @item.name %></td>
      </tr>
      <tr>
        <th>商品説明</th>
        <td><%= @item.explanation %></td>
      </tr>
      <tr>
        <th>ジャンル</th>
        <td><%= @item.genre.name %></td>
      </tr>
      <tr>
        <th>税込価格<br>（税抜価格）</th>
        <td>
          <%= (@item.unit_price.*1.1).round.to_s(:delimited) %>
          (<%= @item.unit_price %>)円
        </td>
      <tr>
        <th> 販売ステータス </th>
        <td>
            <%= @item.is_selling_status_i18n %>

        </td>
      </tr>

      </table>
      <%= link_to "編集する",edit_admin_item_path(@item), class:"btn-btn-success" %>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<h1>注文履歴一覧</h1>