config/routes.rb
Rails.application.routes.draw do

# 会員用
# ↓2023/08/21記入
scope module: :public do
  root to: "homes#top"
  resources :items, only: [:index, :show]
  get "/customers/confirm_withdraw" => "customers#confirm_withdraw"
  get "/customers/mypage" => "customers#show"
  get "/customers/information/edit" => "customers#edit"
  patch "customers/information" => "customers#update"
  patch "/customers/withdraw" => "customers#withdraw"
  delete "/cart_items/destroy_all" => "cart_items#destroy_all"
  resources :cart_items, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :show, :create, :new]
  post "orders/confirm" => "orders#confirm"
  get "orders/complete" => "orders#complete"
  resources :destinations, only: [:index, :edit, :create, :update, :destroy]
  get 'homes/about'

end
# ↑2023/08/21記入
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# ↓2023/08/21記入
namespace :admin do

  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update, :index]
  resources :order_details, only: [:update]
end
# ↑2023/08/21記入

# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  get 'homes/about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :destinations, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    last_name + '' + first_name
  end

  def full_name_kana
    last_name_kana + '' + first_name_kana
  end

  def customer_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :customer
  validates :name, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true, format: {with: /\A\d{7}\z/}, numericality: { only_integer: true }
  
  def destination_display
    '〒' + postal_code + ' ' + name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  enum is_selling_status: { no_selling: 0, selling: 1}

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_datails

  has_one_attached :items_img


  validates :name, presence: true
  validates :is_selling_status, presence: true
  validates :explanation, presence: true
  validates :genre, presence: true
  validates :unit_price, presence: true, numericality: {only_integer: true, greater_than: 0}

  def get_items_image(width, height)
  unless items_img.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    items_img.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  items_img.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  enum how_to_pay: { credit_card: 0, transfer: 1 }
  
  enum status: { 
    Awaiting_Payment: 0,
    Payment_Confirmed: 1,
    In_Production: 2,
    Preparing_for_Shipment: 3,
    Shipped: 4
  }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end 
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
#aaaa
  def index
    @item = Item.new
    @items =Item.all
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    # logger.debug "Received item_params: #{item_params.inspect}"
    @item = Item.new(item_params)
    if @item.save!
      # logger.debug "Received item_params: #{item_params.inspect}"
      flash.now[:success] = "商品の新規登録が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:danger] = "商品の新規登録内容に不備があります。"
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
     if @item.update!(item_params)
       flash.now[:success] = "商品詳細の変更が完了しました。"
       redirect_to admin_item_path(@item)
     else
       flash.now[:danger] = "商品詳細の変更内容に不備があります。"
       render :edit
     end
  end
end

private

  def item_params
    params.require(:item).permit(:genre_id, :name, :explanation, :items_img, :unit_price, :is_selling_status, :is_active)
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NaganoCake</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <script src="https://kit.fontawesome.com/e58d5853a6.js" crossorigin="anonymous"></script>

  <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;700&display=swap" rel="stylesheet">
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <style>
    body {
      font-family: 'Helvetica Neue', Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f5f5f5;
      color: #555;
    }

    header {
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
      padding: 15px 0;
      background-size: cover;
      background-position: center;
      text-align: center;
      color: #fff;
    }

    nav {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    nav ul.navbar-nav {
      list-style: none;
      display: flex;
      padding: 0;
      margin: 0;
    }

    nav ul.navbar-nav li {
      margin: 0 15px;
      display: inline-flex;
      align-items: center;
    }

    nav ul.navbar-nav li a {
      display: inline-block;
      color: #fff;
      text-decoration: none;
      padding: 5px 10px;
    }

    nav a {
      color: #fff;
      text-decoration: none;
    }

    main {
      margin-top: 20px;
      flex: 1;
      padding: 20px;
    }

    footer {
      background-color: #333;
      color: #fff;
      padding: 10px 0;
      text-align: center;
    }

    .logo {
      display: block;
      width: 100px;
      margin-right: 20px;
    }

    .text-blue {
      color: blue;
    }
  </style>
</head>
<body class="d-flex flex-column vh-100">
  <header style="background-image: url('<%= asset_path('header.jpg') %>');" class="py-3">
    <nav>
      <a href="<%= root_path %>">
        <img src="<%= asset_path('logo2.jpg') %>" alt="Logo" class="logo">
      </a>

      <ul class="navbar-nav" style="flex-direction: row;">
        <% if customer_signed_in? %>
          <li><%= link_to "マイページ", customers_mypage_path(current_customer), class: 'nav-link text-blue' %></li>
          <li><%= link_to "商品一覧", items_path, class: 'nav-link text-blue' %></li>
          <li><%= link_to "カート", cart_items_path(current_customer.id), class: 'nav-link text-blue' %></li>
          <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-blue' %></li>
        <% elsif admin_signed_in? %>
          <li><%= link_to '商品一覧', admin_items_path, class: 'nav-link text-blue' %></li>
          <li><%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-blue' %></li>
          <li><%= link_to "注文履歴一覧", admin_orders_path, class: 'nav-link text-blue' %></li>
          <li><%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-blue' %></li>
          <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-blue' %></li>
        <% else %>
          <li><%= link_to 'About', homes_about_path, class: 'nav-link text-blue' %></li>
          <li><%= link_to "商品一覧", items_path, class: 'nav-link text-blue' %></li>
          <li><%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-blue' %></li>
          <li><%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-blue' %></li>
        <% end %>
      </ul>
    </nav>
  </header>

  <main class="mb-auto">
    <%= yield %>
  </main>

  <footer>
    <div class="container text-center">
      <p>&copy; <%= Time.now.year %> NaganoCafe. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>